### ISSUE TITLE
Error running Flash & BatchNormalization tests 

### ISSUE THREAD

**Issue by nravic** [NVIDIA/cudnn-frontend#77]
Hello!

We've been working on a remoting system for CUDA calls that generally works pretty well with most applications, including most `cudnn-frontend` tests. However we've been having issues with a few of the Flash and BatchNorm tests, specifically the following:

```
Flash with rng dropout
Flash with no dropout
Flash backward
BN Finalize Graph
SGBN Add Relu Graph
LayerNorm Training
LayerNorm Inference
SDPA Graph with serialization
Fused scalar
IMMA execution with manual autotuning
BN Finalize
Batch normalization
BF16 LLM Flash MHA Fprop sample
BF16 LLM Flash MHA Bprop sample
```

Which all segfault on `cudnnBackendExecute`. Here's an example stacktrace for one of them: 

```
Thread 6 "gpu-controller" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc1fff000 (LWP 85939)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
383	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
#1  0x00007fff5ece7876 in ?? () from /usr/local/cuda/lib64/libcudnn_engines_runtime_compiled.so.9.1.0
#2  0x00007fff5ece849d in ?? () from /usr/local/cuda/lib64/libcudnn_engines_runtime_compiled.so.9.1.0
#3  0x00007fffc0328345 in cudnn::backend::execute(cudnnContext*, cudnn::backend::ExecutionPlan const&, cudnn::backend::VariantPack&) () from /usr/local/cuda/lib64/libcudnn_graph.so.9.1.0
#4  0x00007fffc03297ef in cudnnBackendExecute () from /usr/local/cuda/lib64/libcudnn_graph.so.9.1.0
#5  0x00005555557934ee in CudaExecutor::wcudnnBackendExecute (
    this=0x555556e36b80 <CudaExecutor::getInstance()::instance>, cudaBuffer=0x300001b8)
    at /home/ubuntu/cedana-gpu/src/gpu-controller/execution/cudnn_execution.cpp:374
#6  0x0000555555754c03 in CudaExecutor::Execute (this=0x555556e36b80 <CudaExecutor::getInstance()::instance>)
    at /home/ubuntu/cedana-gpu/src/gpu-controller/execution/cuda_executor.cpp:1378
 ```

I'm mostly curious if there's anything specific about the way the kernels for Flash or BN are written that would cause an error like this to happen. Inputs to the execute() call in all cases seem to be correct, which were validated by manually printing them out. Memory addresses seem fine as well. 

Thank you!

**Comment by Anerudhan** [comment]
Hi @nravic , 
I see that William and you also have an email thread for the same debug. Lets track this request there. 
Thanks
